### ISSUE TITLE
dynamical word in header title

### ISSUE THREAD

**Issue by Mentos302** [RentalBe/eCom-App#1]
We need to come up with a site's motto. Motto is require last word to be dynamical and changable.

**Comment by Ger4eK** [comment]
RentalBe - сучасний підхід до оренди речей / комфорту / затишку / мрії

**Comment by Ger4eK** [comment]
Сильно нє ?

**Comment by Mentos302** [comment]
Thank you, Oleg, nice work! But we decide to choose current version `RentalBe - сучасний підхід речей до користування`
